/** */
/*
/*   Allowed params specified in documentation NEWSApi to fill select boxes
/*    
/**** */

const newsApiAllowedParams = {
            
            categories  :[ { code: ''              , option: 'No Filter'},
                           { code: 'general'       , option:'General' },
                           { code: 'business'      , option:'Business' },
                           { code: 'entertainment' , option:'Entertainment' },
                           { code: 'health'        , option:'Health' },
                           { code: 'science'       , option:'Science' },
                           { code: 'sports'        , option:'Sports' },
                           { code: 'technology'    , option:'Technology' }],

            languages   :[{ code: ''   , option: 'No Filter'},
                          { code: 'ar' , option: 'Arabic' },
                          { code: 'de' , option: 'German' },
                          { code: 'en' , option: 'English' },
                          { code: 'es' , option: 'Spanish' },
                          { code: 'fr' , option: 'French' },
                          { code: 'he' , option: 'Hebrew' },
                          { code: 'it' , option: 'Italian' },
                          { code: 'nl' , option: 'Dutch' },
                          { code: 'no' , option: 'Norwegian' },
                          { code: 'pt' , option: 'Portuguese' },
                          { code: 'ru' , option: 'Russian' },
                          { code: 'se' , option: 'Sami' },
                          { code: 'zh' , option: 'Chinese' }],
      
            countries   :[{ code: ''   , option: 'No Filter'},
                          { code: 'AR' , option: 'Argentina' },
                          { code: 'AT' , option: 'Austria' },
                          { code: 'AU' , option: 'Australia' },
                          { code: 'BE' , option: 'Belgium' },
                          { code: 'BG' , option: 'Bulgaria' },
                          { code: 'BR' , option: 'Brazil' },
                          { code: 'CA' , option: 'Canada' },
                          { code: 'CH' , option: 'Switzerland' },
                          { code: 'CN' , option: 'China' },
                          { code: 'CO' , option: 'Colombia' },
                          { code: 'CU' , option: 'Cuba' },
                          { code: 'CZ' , option: 'Czech Republic' },
                          { code: 'DE' , option: 'Germany' },
                          { code: 'EG' , option: 'Egypt' },
                          { code: 'FR' , option: 'France' },
                          { code: 'GB' , option: 'United Kingdom' },
                          { code: 'GR' , option: 'Greece' },
                          { code: 'HK' , option: 'Hong Kong' },
                          { code: 'HU' , option: 'Hungary' },
                          { code: 'ID' , option: 'Indonesia' },
                          { code: 'IE' , option: 'Ireland' },
                          { code: 'IL' , option: 'Israel' },
                          { code: 'IN' , option: 'India' },
                          { code: 'IT' , option: 'Italy' },
                          { code: 'JP' , option: 'Japan' },
                          { code: 'KR' , option: 'South Korea' },
                          { code: 'LT' , option: 'Lithuania' },
                          { code: 'LV' , option: 'Latvia' },
                          { code: 'MA' , option: 'Morocco' },
                          { code: 'MX' , option: 'Mexico' },
                          { code: 'MY' , option: 'Malaysia' },
                          { code: 'NG' , option: 'Nigeria' },
                          { code: 'NL' , option: 'Netherlands' },
                          { code: 'NO' , option: 'Norway' },
                          { code: 'NZ' , option: 'New Zealand' },
                          { code: 'PH' , option: 'Philippines' },
                          { code: 'PL' , option: 'Poland' },
                          { code: 'PT' , option: 'Portugal' },
                          { code: 'RO' , option: 'Romania' },
                          { code: 'RS' , option: 'Serbia' },
                          { code: 'RU' , option: 'Russia' },
                          { code: 'SA' , option: 'Saudi Arabia' },
                          { code: 'SE' , option: 'Sweden' },
                          { code: 'SG' , option: 'Singapore' },
                          { code: 'SI' , option: 'Slovenia' },
                          { code: 'SK' , option: 'Slovakia' },
                          { code: 'TH' , option: 'Thailand' },
                          { code: 'TR' , option: 'Turkey' },
                          { code: 'TW' , option: 'Taiwan' },
                          { code: 'UA' , option: 'Ukraine' },
                          { code: 'AE' , option: 'United Arab Emirates' },
                          { code: 'US' , option: 'United States' },
                          { code: 'VE' , option: 'Venezuela' },
                          { code: 'ZA' , option: 'South Africa' }]
}

export default newsApiAllowedParams
